---
filters:
    - multibib
validate-yaml: false
bibliography:
    pubs: assets/pubs.bib
    preprints: assets/preprints.bib
    software: assets/software.bib
    conferences: assets/conferences.bib
bibliographystyle: apa
nocite:
    pubs: '@*'
    preprints: '@*'
    software: '@*'
    conferences: '@*'
---

```{=html}
<div style="justify-content: center; display: flex; align-items: center;">
    <a href="latex/main.pdf" download="chris_donovan_cv">
        <button class="btn">
            <i class="fa fa-download"></i>
            Download CV
        </button>
    </a>
</div>
```

# Chris Donovan

## Research Statement

I am a food systems data scientist with an interdisciplinary background in environmental science, economics, and behavior. My strengths include quantitative analysis and modeling, with a particular emphasis on open data and reproducible workflows. I contribute to the advancement of scientific rigor and accessibility by developing and applying methods that enable data to be shared, validated, and used across disciplines. Through this work, I help generate insights that support more sustainable, transparent, and equitable social-ecological systems.

## Education

```{=html}
<div style="display: grid; grid-template-columns: 70% 30%; gap: 1rem 2rem; align-items: start;">
    <div>
        <strong>M.S., Community Development and Applied Economics</strong><br>
        Department of Community Development and Applied Economics<br>
        University of Vermont<br>
        Burlington, Vermont<br>
    </div>
    <div>2024</div>

    <div>
        <strong>Graduate Certificate, Ecological Economics</strong><br>
        Department of Community Development and Applied Economics<br>
        University of Vermont<br>
        Burlington, Vermont<br>
    </div>
    <div>2024</div>

    <div>
        <strong>B.S., Environmental Science, Emphasis in Conservation Biology</strong><br>
        Prescott College<br>
        Prescott, Arizona
    </div>
    <div>2019</div>

</div>
```

## Work History

```{=html}
<div style="display: grid; grid-template-columns: 60% 40%; gap: 1rem 2rem; align-items: start;">

    <div>
        <strong>Food Systems Data Scientist</strong><br>
        Food Systems Research Institute<br>
        University of Vermont<br>
        Burlington, Vermont
    </div>
    <div>September 2024 – Present</div>

    <div>
        <strong>Graduate Research Assistant</strong><br>
        Community Development and Applied Economics<br>
        University of Vermont<br>
        Burlington, Vermont
    </div>
    <div>September 2022 - September 2024</div>

    <div>
        <strong>Rare Plant Survey Crew Leader</strong><br>
        Institute for Applied Ecology<br>
        Boise, Idaho
    </div>
    <div>April 2022 - August 2022</div>

    <div>
        <strong>Precision Restoration Technician</strong><br>
        The Nature Conservancy<br>
        Lander, Wyoming
    </div>
    <div>April 2020 - April 2022</div>

    <div>
        <strong>Environmental Services Intern</strong><br>
        Ocotillo Wells SVRA<br>
        Ocotillo Wells, California
    </div>
    <div>November 2019 - March 2020</div>

    <div>
        <strong>Seed Technician</strong><br>
        Institute for Applied Ecology<br>
        Silver City, New Mexico
    </div>
    <div>August 2019 - November 2019</div>

    <div>
        <strong>Botanical Field Technician</strong><br>
        Great Basin Institute<br>
        Las Vegas, Nevada
    </div>
    <div>May 2019 - August 2019</div>

</div>
```

## Publications

### Peer-Reviewed {style="border-bottom: none !important;"}

::: {#refs-pubs}
:::

### Preprint {style="border-bottom: none !important;"}

::: {#refs-preprints}
:::

## Conference Presentations

::: {#refs-conferences}
:::

## Software

* <a href="https://www.github.com/tshrum/rebl" target="_blank">REBL Scale R Package</a>
* <a href="https://www.github.com/ChrisDonovan307/reblcalc" target="_blank">REBL Calculator Shiny App</a>
* <a href="https://www.github.com/Food-Systems-Research-Institute/SMexplorer" target="_blank">SMexplorer Shiny App</a>
* <a href="https://www.github.com/Food-Systems-Research-Institute/SMdocs" target="_blank">SMdocs Website</a>
* <a href="https://www.github.com/Food-Systems-Research-Institute/SMdata" target="_blank">SMdata R Package</a>
* <a href="https://www.github.com/ChrisDonovan307/grade_analysis_app" target="_blank">Grade Analysis Shiny App</a>
* <a href="https://www.github.com/ChrisDonovan307/projecter" target="_blank">Projector R Package</a>

